In [1]:
### libaries 

In [2]:
### numpy , pandas and matplotlib

In [3]:
import numpy as np

In [4]:
numbers = [10,20,30]

In [6]:
arr = np.array(numbers)

In [7]:
arr

array([10, 20, 30])

In [8]:
arr + 2

array([12, 22, 32])

In [9]:
arr * 2

array([20, 40, 60])

In [10]:
arr.shape

(3,)

In [12]:
arr

array([10, 20, 30])

In [14]:
arr[arr > 11]

array([20, 30])

In [15]:
arr.size

3

In [16]:
arr.mean()

20.0

In [17]:
arr.std()

8.16496580927726

In [18]:
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '

In [19]:
arr.var()

66.66666666666667

In [20]:
num2 = [10,20,30,40]

In [24]:
arr2 = np.array(num2)

In [25]:
arr2.shape

(4,)

In [26]:
arr2

array([10, 20, 30, 40])

In [29]:
arr2.reshape(1,4)

array([[10, 20, 30, 40]])

In [30]:
### use numpy arange , linspace 

In [33]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [36]:
np.linspace(0,4,10)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [37]:
### pandas

In [40]:
### Series
### DataFrame


In [39]:
import pandas as pd

In [49]:
val = [10,20,20,30]

In [50]:
ser = pd.Series(val,name="money")

In [51]:
ser

0    10
1    20
2    20
3    30
Name: money, dtype: int64

In [52]:
ser.mean()

20.0

In [53]:
ser.mode()

0    20
Name: money, dtype: int64

In [54]:
ser.sum()

80

In [55]:
ser.std()

8.16496580927726

In [56]:
ser * 2

0    20
1    40
2    40
3    60
Name: money, dtype: int64

In [57]:
ser + 10

0    20
1    30
2    30
3    40
Name: money, dtype: int64

In [59]:
ser[ser > 10]

1    20
2    20
3    30
Name: money, dtype: int64

In [60]:
### dataframe

In [67]:
amount = [10,20,30]
prod = ["mango","orange","apple"]

In [68]:
df = pd.DataFrame({"amount":amount,"product":prod})

In [69]:
df

amount product
0      10   mango
1      20  orange
2      30   apple

In [77]:
df[df["amount"] > 20]

amount product
2      30   apple

In [78]:
df

amount product
0      10   mango
1      20  orange
2      30   apple

In [82]:
df.tail(2)

amount product
1      20  orange
2      30   apple

In [85]:
df[df['product'] == "mango"]

amount product
0      10   mango